name: Review pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Review deployment
    runs-on: ubuntu-latest
    env:
      api-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install ./api dependencies
        run: npm ci
        working-directory: ${{ env.api-directory }}
      - name: Build documentation
        run: npm run build:docs
        working-directory: ${{ env.api-directory }}

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
